Repository radhika-droid/PeerPrep, pull requests merged in 2025-08, with the labels that each got.

#10 Create License
  License
Labels: Gssoc, level1

#8 Add .gitignore file to exclude unnecessary files
  .gitignore
Labels: Gssoc, level1

#15 chore(security): move SECRET_KEY to .env using python-decouple
  .env
  peerprep/__pycache__/__init__.cpython-312.pyc
  peerprep/__pycache__/settings.cpython-312.pyc
  peerprep/__pycache__/urls.cpython-312.pyc
  peerprep/__pycache__/wsgi.cpython-312.pyc
Labels: good first issue, Gssoc, level1

#41 Added contributors carousel in about.html
  templates/about.html
Labels: level2, gssoc25

#42 Update README.md
  README.md
Labels: level1, gssoc25

#47 Added snake-style cursor trail effect across all pages
  static/css/index.css
  static/js/cursorTrail.js
  templates/about.html
  templates/base.html
  templates/footer.html
Labels: level2, gssoc25

#55 Fixed logout (Closes #54)
  core/templates/dashboard.html
  core/templates/index.html
  db.sqlite3
Labels: enhancement, good first issue, level2, gssoc25

#66 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: level2, gssoc25

#72 Added Social media icon
  core/templates/footer.html
Labels: level1, gssoc25
